version: 1
formatters:
  consoleFormatter:
    format: '%(asctime)s - ROOT(%(name)s) - %(levelname)s - %(message)s'
  fileFormatter:
    format: '%(asctime)s: %(levelname)s - %(name)s - %(message)s'
    datefmt: '%d %b %Y, %H:%M:%S'
  colourConsoleFormatter:
    class: colorlog.ColoredFormatter
    format: '%(log_color)s%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: consoleFormatter
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: WARNING
    formatter: fileFormatter
    filename: file.log
  colourConsole:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colourConsoleFormatter
loggers:
  root:
    level: DEBUG
    handlers: [console]
  sampleLogger:
    level: DEBUG
    handlers: [file]
    propagate: yes
  appLogger:
    level: INFO
    handlers: [colourConsole, file]
    propagate: no